apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-viz
    targetRevision: 30.12.7
    helm:
      releaseName: linkerd-viz
      values: |-
        prometheusUrl: http://monitoring-prometheus.monitoring.svc.cluster.local:9090
        jaegerUrl: http://jaeger-query.jaeger.svc.cluster.local
        dashboard:
          enforcedHostRegexp: linkerd-viz.local.devops
        grafana:
          externalUrl: https://grafana.local.devops
        tap:
          externalSecret: true
          injectCaFrom: linkerd-viz/tap
        tapInjector:
          externalSecret: true
          injectCaFrom: linkerd-viz/linkerd-tap-injector
        prometheus:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
