apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: sonarqube-db-backup
  namespace: sonarqube
spec:
  schedule: "0 12 0 * * *"
  backupOwnerReference: self
  cluster:
    name: sonarqube
