apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  instances: 3
  bootstrap:
    initdb:
      database: sonarqube
      owner: sonarqube
  backup:
    barmanObjectStore:
      destinationPath: s3://sonarqube-psql/
      endpointURL: http://minio.minio.svc.cluster.local:9000
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: accesskey
        secretAccessKey:
          name: minio-creds
          key: secretkey
    retentionPolicy: "3d"
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
