apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: sonarqube
    targetRevision: 4.1.6
    helm:
      releaseName: sonarqube
      values: |-
        nameOverride: sonarqube
        fullnameOverride: sonarqube
        sonarqubeUsername: user
        existingSecret: admin
        service:
          type: NodePort
        postgresql:
          enabled: false
        externalDatabase:
          host: sonarqube-rw
          existingSecret: sonarqube-app
          existingSecretPasswordKey: password
          database: sonarqube
          port: 5432
          user: sonarqube
        ingress:
          enabled: true
          pathType: ImplementationSpecific
          ingressClassName: nginx
          hostname: sonarqube.local.devops
          path: /
          annotations:
            cert-manager.io/cluster-issuer: local.devops
          tls: true
          selfSigned: false
        metrics:
          jmx:
            enabled: true
          serviceMonitor:
            enabled: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
