---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: argo
spec:
  encryptedData:
    accesskey: AgA7oM4yvGYSxSRGmY9v5g9Wr+5/6Blth89y1U69lLGW6uLhba/CimNNuRrHI6DrxCEA8UkL/Gkj5L/ljX9IIagx1Zgc0t/w4lHwC8vPIUkSZ4Tp4Raqp7Da3w1+axNzs3ZkWTx6VBeS5epwA+Fb8I14NaAIUar5F2jZGFRg3uijILp62yHFbBy7AS/EgpvApZk06fQM8P2pJNFgfdkfpfOn0YuiWVgf7tOZyCRUnkV5p9HWavpb/kNXL7M3SkTT43rWnT5gXsiw5PlawCF2EBgB0s+RV1ZuUMPvaysKh0XN1VRJoXoL6cPcUIMeYOnJmsqdX/Eg/sXNyKzVPuJKxcaZfG2QTt4NirqiLtQ9NzQUgQb5jDmiFCNewUB93m2yLvdiYPlhWGvDFynWR8U/grMx6/VJYWKKhTJc6hL5XCbPKtc1hNCrBu9X3MARsR4nIx9X/yYVC/yQEyE5m5uaPdWVsQ0tJCxU7+jtCfjF9pnnoc0go9ntRw9JCH6HCnzhGoM941Sl0Nq+1n7GhgkRFDCFSb+Vkzom3PUSTFn5aj1rAImH1GuOY+N2wADXoRDawBk1o/0URxiDdEli/fkL8SLnMUGEC2nMAu+QqSduJB8YjnTvMLxzhHnwbi7XfCTpOKOmw2iSv3pgqqcKq5znwjRjTWzkeInmQyMDL3pG1wWpEG/RWaom4Bc9W5cvsuRQybPQ77IGZg==
    secretkey: AgArA6koiaicIEfLlvqZsL3MJik7J3rEt7sYRJh63L9A7d0s9eBMi2lzohr2vyaWFLUUbtLYPrxkJ4Wifj2hvTRfISq5qok+klpgTHjx0gPf9fOS9AbM44Ov5ev+jynvjafUnXbdOJfF7jJIlqOKTmR7aI2UK9mZrgSqasNi648kx678DL9lfG/HTgZVL1RM1Ai1qzqVD2EOkc5cS3vNXpX4SkK3xiBHAy0eoyECEX454BwhRQizSmvuqikuohZwVhVuC8fmbFibAhbffTr2lz4ufqEmfzBMcL0xTlU+g3a+th6MejyTCAP+uyJ6RHlR9x1qg3ufx0t15NE/3DYa9sCSC0YoYAB699uF27G2h04V2FLJkSEmsPTTxsuuNFMwnUce1gJ6pMDxhZgqjg8z9MxdMlbr21qmwaEq7EGOGgWYBUUBzDepVV0qSPwKUv8QogrccIAXgKBeEoNqP6abl0rd9L9aaNQ3dtCd6W6H227GONP23mInj4/5tv61vPRvz6gEJlrfPaLFp3wgBU4iHxT0VBlxsLZHuSnP7AKJZAivcHcCRpIvvZ2OW6uWKcr0tt9+ewKDpDYwB4C1eY0KqxY/ofuJLma4Vv5BTgzDwxANB2q8mdHTAJUt0fWOXVX0o0ltYjo+kPKQ3bzbpxtxr9ZNKrL6dJfieMPAzEBM0lV4cYiMEIRlsPUboq+w9o4l5waTkCDcTmgMtst8
  template:
    metadata:
      creationTimestamp: null
      name: minio
      namespace: argo
