apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.13.3
    helm:
      releaseName: sealed-secrets
      values: |-
        nameOverride: "sealed-secrets"
        fullnameOverride: "sealed-secrets"
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
